### ISSUE TITLE
Feat: Add support for crediting doll makers for art.

### ISSUE THREAD

**Issue by EmmiaSilk** [EmmiaSilk/character-notes#8]
One of the ways art of characters is created is through use of a dollmaker or art generator such as Picrew. It is important to credit these dollmakers, so a system must be added for providing credit. 

The credits will be provided using the `generator` field on art pages. This field is a list of entries with a set of values:
- `name` - Includes the name of the dollmaker and, if necessary, it's website. (For example: "Taeko-style girl (Picrew)")
- `url` - The URL of the dollmaker. (For example: https://picrew.me/image_maker/196270/ )

For example, in the front matter of an art page:
```yaml
generator: 
  - name: Taeko-style girl (Picrew)
    url: https://picrew.me/image_maker/196270/
```

## Goals: 
- [x] Add a field in art layouts for picrew generator listings
- [x] In art pages, display the dollmakers (or list of dollmakers) used to create the image
